[package]
name = "usbd-midi"
version = "0.2.0"
authors = ["beau trepp <beautrepp@gmail.com>"]
edition = "2018"
description = "A usb-midi implementation for usb-device"
homepage = "https://github.com/btrepp/usbd-midi"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
embedded-hal = "0.2.4"
nb = "1.0.0"
usb-device = "0.2.7"
